#!/usr/bin/env python
# -*- coding: utf-8 -*-

def primechecker(n):
    for i in range(2,int(n**0.5)+1):
        if n%i==0:
            return f"{n} is not a prime number"

    return f"{n} is a prime number"

def interact():
    print("Input any number")
    n = input()
    n = int(n)
    x = primechecker(n)
    print(x)

# if __name__ == '__main__':
#     print("Input any number")
#     n = input()
#     n = int(n)
#     x = primechecker(n)
#     print(x)

interact()
